export class Indicador {
  constructor({ INDICADORES_ID, EJES_ID, INDICADORES_NOMBRE, INDICADORES_DESCRIPCION, INDICADORES_VALOR }) {
    this.INDICADORES_ID = INDICADORES_ID;
    this.EJES_ID = EJES_ID;
    this.INDICADORES_NOMBRE = INDICADORES_NOMBRE;
    this.INDICADORES_DESCRIPCION = INDICADORES_DESCRIPCION;
    this.INDICADORES_VALOR = INDICADORES_VALOR;
  }
}
