export class ReporteProyecto {
  constructor({ REPORTEPROYECTO_ID, USUARIO_ID, REPORTEPROYECTO_NOMBRE, REPORTEPROYECTO_FECHAINICIO, REPORTEPROYECTO_FECHAFIN, REPORTEPROYECTO_PERIODOSUBIRREPORTES, REPORTEPROYECTO_ACCIONESDESTACADAS, REPORTEPROYECTO_PRIMERHITO, REPORTEPROYECTO_SEGUNDOHITO, REPORTEPROYECTO_TERCERHITO, REPORTEPROYECTO_NOMBREHITO, REPORTEPROYECTO_LUGAR, REPORTEPROYECTO_DESCRIPCION, REPORTEPROYECTO_INDICADORLARGOPLAZO, REPORTEPROYECTO_MATERIALAUDIOVISUAL, REPORTEPROYECTO_INDICADORPREVENCION, REPORTEPROYECTO_ESTADO }) {
    this.REPORTEPROYECTO_ID = REPORTEPROYECTO_ID;
    this.USUARIO_ID = USUARIO_ID;
    this.REPORTEPROYECTO_NOMBRE = REPORTEPROYECTO_NOMBRE;
    this.REPORTEPROYECTO_FECHAINICIO = REPORTEPROYECTO_FECHAINICIO;
    this.REPORTEPROYECTO_FECHAFIN = REPORTEPROYECTO_FECHAFIN;
    this.REPORTEPROYECTO_PERIODOSUBIRREPORTES = REPORTEPROYECTO_PERIODOSUBIRREPORTES;
    this.REPORTEPROYECTO_ACCIONESDESTACADAS = REPORTEPROYECTO_ACCIONESDESTACADAS;
    this.REPORTEPROYECTO_PRIMERHITO = REPORTEPROYECTO_PRIMERHITO;
    this.REPORTEPROYECTO_SEGUNDOHITO = REPORTEPROYECTO_SEGUNDOHITO;
    this.REPORTEPROYECTO_TERCERHITO = REPORTEPROYECTO_TERCERHITO;
    this.REPORTEPROYECTO_NOMBREHITO = REPORTEPROYECTO_NOMBREHITO;
    this.REPORTEPROYECTO_LUGAR = REPORTEPROYECTO_LUGAR;
    this.REPORTEPROYECTO_DESCRIPCION = REPORTEPROYECTO_DESCRIPCION;
    this.REPORTEPROYECTO_INDICADORLARGOPLAZO = REPORTEPROYECTO_INDICADORLARGOPLAZO;
    this.REPORTEPROYECTO_MATERIALAUDIOVISUAL = REPORTEPROYECTO_MATERIALAUDIOVISUAL;
    this.REPORTEPROYECTO_INDICADORPREVENCION = REPORTEPROYECTO_INDICADORPREVENCION;
    this.REPORTEPROYECTO_ESTADO = REPORTEPROYECTO_ESTADO;
  }
}
