export class Usuario {
  constructor({ USUARIO_ID, USUARIO_NOMBREONG, USUARIO_USER, USUARIO_CONTRASENA, USUARI_DESCRIPCION }) {
    this.USUARIO_ID = USUARIO_ID;
    this.USUARIO_NOMBREONG = USUARIO_NOMBREONG;
    this.USUARIO_USER = USUARIO_USER;
    this.USUARIO_CONTRASENA = USUARIO_CONTRASENA;
    this.USUARI_DESCRIPCION = USUARI_DESCRIPCION;
  }
}
